from io import BytesIO
from typing import Dict, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

def generate_official_pdf(report: Dict, qr_png: Optional[bytes] = None) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, height - 2.2*cm, "ISTIDAMA | Investment Valuation Report")
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, height - 2.9*cm, "Internal Use Only - 2026")
    c.line(2*cm, height - 3.2*cm, width - 2*cm, height - 3.2*cm)

    y = height - 4.2*cm
    fields = [
        ("Contract ID", str(report.get("contract_id", ""))),
        ("Activity", str(report.get("activity", ""))),
        ("Land Area (m2)", f"{report.get('land_area', 0):,.0f}"),
        ("Zone", str(report.get("zone", ""))),
        ("Term (years)", str(report.get("term_years", ""))),
        ("Grace (years)", str(report.get("grace_years", ""))),
        ("Base Rent (SAR/year)", f"{report.get('base_rent', 0):,.0f}"),
        ("Rule", "5% every 5 years (Art. 26)"),
    ]

    for label, value in fields:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(2*cm, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(7.2*cm, y, value)
        y -= 0.8*cm

    y -= 0.2*cm
    c.setFont("Helvetica", 9)
    c.drawString(2*cm, y, "Generated by Istidama Platform - Based on valuation policy and municipal assets regulation.")
    y -= 0.5*cm
    c.setFont("Helvetica-Oblique", 8.5)
    c.drawString(2*cm, y, "For full Arabic text, use the in-app report section.")

    if qr_png:
        try:
            img = ImageReader(BytesIO(qr_png))
            c.drawImage(img, width - 6.5*cm, 2.2*cm, 4.5*cm, 4.5*cm, preserveAspectRatio=True, mask='auto')
            c.setFont("Helvetica", 8)
            c.drawString(width - 6.5*cm, 1.8*cm, "Verification QR")
        except Exception:
            pass

    c.setFont("Helvetica", 8)
    c.drawRightString(width - 2*cm, 1.5*cm, "Istidama • Makkah • 2026")
    c.showPage()
    c.save()
    return buf.getvalue()
